### ISSUE TITLE
Don't copy entire addons folder during deploy

### ISSUE THREAD

**Issue by jonttm** [leighmacdonald/uncletopia#5]
We should move the original task to pre.
```
- name: Copy Source Mods
  synchronize:
    src: tf/addons/
    dest: serverfiles/tf/addons/
    owner: false
    group: false
    recursive: true
    delete: true
```

We should add 2 new entries to deploy for now. More can be added in the future when needed.
```
- name: Copy source mod configs
  copy:
    src: tf/addons/sourcemod/configs/
    dest: serverfiles/tf/addons/sourcemod/configs/
    owner: tf2server
    group: tf2
    mode: 0664
```
```
- name: Copy source mod plugins
  copy:
    src: tf/addons/sourcemod/plugins/
    dest: serverfiles/tf/addons/sourcemod/plugins/
    owner: tf2server
    group: tf2
    mode: 0664
```

Edit: Try removing `addons/sourcemod/logs` from synchronize instead of just updating plugins/configs
